server:
  # 配置接口为https，部署后方可生效，本地不会显示
  ssl:
    key-store: classpath:pcdd.work.jks
    key-store-password: 2m6163u80ah
    key-store-type: JKS
  http2:
    enabled: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_api?
      serverTimezone=Asia/Shanghai
      &useUnicode=true
      &characterEncoding=utf-8
      &useSSL=true
    username: root
    password: root

  redis:
    database: 15
    host: 192.168.22.133
    port: 6379
    password: root
    # 连接超时时间（毫秒）
    timeout: 5000
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 4
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 32
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms




