spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vueblog?
      serverTimezone=Asia/Shanghai
      &useUnicode=true
      &characterEncoding=utf-8
      &useSSL=true
    username: root
    password: root

  redis:
    database: 15
    host: 127.0.0.1
    port: 6379
    password: root
    # 连接超时时间（毫秒）
    timeout: 5000
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 4
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 32
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms




